source 'https://rubygems.org'

gem 'rspec'
gem 'guard'
gem 'guard-rspec'
gem 'rb-fsevent', require: false

gem 'rspec-its'
gem 'fuubar'
gem 'terminal-notifier', '1.6.3'
gem 'terminal-notifier-guard', '1.6.3'
